name: Linux Build
on: [push]

jobs:
  build:
    name: Ubuntu Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: sudo apt-get update
      - run: sudo apt-get install -y g++-8 ninja-build libboost-all-dev libzip-dev libwxgtk3.0-dev libprocps-dev
      - run: pip3 install meson
      - run: meson setup --buildtype minsize rbuild
        env:
          CC: gcc-8
          CXX: g++-8
      - run: ninja -v -C rbuild
      - run: strip -s rbuild/trollauncher
      - run: ./package/linux/make_package.sh
      - uses: actions/upload-artifact@v2
        with:
          path: 'package/linux/trollauncher_*_amd64.deb'
