name: Linux Build
on: [push]

jobs:
  build:
    name: Ubuntu Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: sudo apt-get update
      - run: sudo apt-get install -y ninja-build libboost-all-dev libzip-dev libwxgtk3.0-dev
      - run: pip3 install meson
      - run: meson setup --buildtype minsize rbuild
      - run: ninja -v -C rbuild
      - run: strip -s rbuild/trollauncher
